import { createHash } from "node:crypto";
import type { NewsItem,RawNewsItem,SourceConfig,StoryCluster,PendingPost,RiskLevel } from "./types";
const STOP=new Set(["ve","ile","bir","the","a","an","of","in","to","son","dakika"]);
export const canonicalizeUrl=(input:string)=>{const u=new URL(input);u.hash="";[...u.searchParams.keys()].filter(k=>k.startsWith("utm_")||["fbclid","gclid"].includes(k)).forEach(k=>u.searchParams.delete(k));u.hostname=u.hostname.toLowerCase();u.pathname=u.pathname.replace(/\/$/,"")||"/";return u.toString()};
export const fingerprint=(text:string)=>createHash("sha256").update(text.toLocaleLowerCase("tr").normalize("NFKD").replace(/[^a-z0-9çğıöşü\s]/gi," ").split(/\s+/).filter(w=>w&&!STOP.has(w)).sort().join(" ")).digest("hex");
export const similarity=(a:string,b:string)=>{const A=new Set(a.toLocaleLowerCase("tr").split(/\W+/).filter(x=>x&&!STOP.has(x))),B=new Set(b.toLocaleLowerCase("tr").split(/\W+/).filter(x=>x&&!STOP.has(x)));const common=[...A].filter(x=>B.has(x)).length;return common/Math.max(1,A.size+B.size-common)};
const breakingTerms=/breaking|son dakika|acil|deprem|saldırı|istifa|öldü|ateşkes|faiz kararı/i;
const highImpact=/deprem|savaş|saldırı|seçim|faiz|merkez bank|hükümet|nükleer|ateşkes/i;
export function normalize(raw:RawNewsItem,source:SourceConfig,now=new Date()):NewsItem{const url=canonicalizeUrl(raw.url);const freshness=Math.max(0,30-Math.floor((now.getTime()-new Date(raw.publishedAt).getTime())/60000));const breaking=Math.min(100,Math.round(source.priority*.45+freshness+(breakingTerms.test(raw.title)?25:0)));const importance=Math.min(100,Math.round(source.trustScore*.45+source.priority*.25+(highImpact.test(raw.title)?25:5)));const turkey=/türkiye|turkey|ankara|istanbul|malatya|türk/i.test(raw.title)?90:20;return{...raw,id:`item_${createHash("sha1").update(source.id+raw.externalId).digest("hex").slice(0,16)}`,sourceId:source.id,sourceName:source.name,sourceTier:source.sourceType==="official"?"OFFICIAL":source.priority>=90?"A":"B",sourceTrustScore:source.trustScore,canonicalUrl:url,discoveredAt:now.toISOString(),category:highImpact.test(raw.title)?"breaking":"world",entities:[],claims:[{text:raw.title,type:"reported_fact",supportingSources:[source.id],contradictingSources:[],confidence:source.trustScore,attributionRequired:source.sourceType!=="official"}],breakingScore:breaking,importanceScore:importance,confidenceScore:source.trustScore,turkeyRelevanceScore:turkey,rawPayloadHash:createHash("sha256").update(JSON.stringify(raw.raw)).digest("hex"),processingStatus:"normalized"}}
export function findCluster(item:NewsItem,clusters:StoryCluster[],titles:Map<string,string>){return clusters.find(c=>c.fingerprint===fingerprint(item.title)||c.itemIds.some(id=>similarity(item.title,titles.get(id)??"")>=.55))}
export function publicationDecision(item:NewsItem,corroborating:number,risk:RiskLevel,mode="hybrid"){if(mode==="manual"||risk==="high")return"MANUAL";if((item.sourceTier==="A"||item.sourceTier==="OFFICIAL")&&item.confidenceScore>=90&&item.importanceScore>=85)return"FAST";if(item.confidenceScore>=75&&corroborating>=2)return"CONFIRM";return"MANUAL"}
export function createPost(item:NewsItem,clusterId:string,mode:"FAST"|"CONFIRM"|"MANUAL",text:string,count:number):PendingPost{return{id:`post_${fingerprint(clusterId+text).slice(0,16)}`,clusterId,text,weightedCharacterCount:count,sourceIds:[item.sourceId],importanceScore:item.importanceScore,breakingScore:item.breakingScore,confidenceScore:item.confidenceScore,publishMode:mode,generatedAt:new Date().toISOString(),status:mode==="MANUAL"?"awaiting_review":"ready"}}
